#! /bin/ksh

cols=${1:-80}
dec=1
tens=1
hunreds=0
while [ $cols -ge 10 ]; do
        echo "123456789${dec}\c"
        (( tens = ( $tens + 1 ) % 10 ))
        if [ $tens -eq 0 ]; then
                (( ++hundreds ))
                dec=`expr substr $hundreds 1 1`
        else
                dec=$tens
        fi
        (( cols = $cols - 10 ))
done
case $cols in
  9) echo 123456789;;
  8) echo 12345678;;
  7) echo 1234567;;
  6) echo 123456;;
  5) echo 12345;;
  4) echo 1234;;
  3) echo 123;;
  2) echo 12;;
  1) echo 1;;
  0) echo ;;
esac
